[build-system]
requires = [
    "setuptools>=42", 
    "wheel", 
    "scikit-build",
    "pybind11",
    "cmake>=3.12", 
    "ninja; platform_system!='Windows'",
]
build-backend = "setuptools.build_meta"
