[build-system]
requires = [
    "setuptools", 
    "wheel", 
    "scikit-build",
    "pybind11",
    "cmake", 
  "ninja; platform_system!='Windows'",
    "igraph"
]
build-backend = "setuptools.build_meta"
