name: Publish HTML Documentation

on:
  push:
    branches:
      - master
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    name: Build & Publish Documentation to GitHub Pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./_skbuild
            ./vendor/igraph
          key: ${{ runner.os }}-pip-3.10.6-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.10.6-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install dev dependencies
        run: sudo apt-get install bison flex

      - name: Generate Documentation
        run: ./bin/make-docs.sh

      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs-html/ # The folder the action should deploy.
