name: Run Tests on Windows

on:
  push:
    branches:
      - workflow_dispatch

jobs:
  build-deploy:
    runs-on: windows-latest

    name: Run Python + C++ Tests on Windows
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: "recursive"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pip'

      - uses: actions/cache@v2
        with:
          path: |
            .\vendor\nlopt
            .\tests\build
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\Temp\chocolatey
            .\vendor\igraph
            .\_skbuild
          key: ${{ runner.os }}-py-3.10.6-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-3.10.6-

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install -y winflexbison3 eigen lcov
      
      - name: Build
        run: pip install . --verbose

      - name: Run Tests
        run: python -m coverage run -m unittest discover -v
