name: Run Tests on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: windows-latest

    name: Run Python + C++ Tests on Windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
          cache: "pip"

      - uses: actions/cache@v3
        with:
          path: |
            .\vendor\*-Windows
            .\tests\build
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\Temp\chocolatey
            .\vendor\igraph
            .\_skbuild
          key: ${{ runner.os }}-py-3.12.4-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-3.12.4-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y winflexbison3 eigen lcov

      - name: Build
        run: pip install . --verbose

      - name: Run Tests
        run: python -m coverage run -m unittest discover -v
